server:
  port: 8091

  eureka:
    instance:
      hostname: localhost

Spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      routes:
        - id: service
          uri: lb://service
          predicates:
            - Path=/user/**
        - id: contact
          uri: lb://contact
          predicates:
            - Path=/contacts/**